# 
FROM svizor/zoomcamp-model:3.9.12-slim

# 
WORKDIR /app

# 
COPY ./model ./model

# 
RUN pip install fastapi==0.88
RUN pip install pydantic==1.10.2
RUN pip install uvicorn==0.20.0
RUN pip install tensorflow==2.9.1
RUN pip install numpy==1.22.3
RUN pip install pillow==9.2.0
RUN pip install python-multipart
RUN pip install telebot
RUN pip install chardet 
RUN pip install requests 
RUN pip install pytelegrambotapi
# 
COPY ./* ./

# 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
